server:
mybatis:   
   #config-location: classPath:mybatis/mybatis.cfg.xml   #mybatis配置文件所在路径
   type-aliases-package: com.liubin.springcloud.entities  #所有Entity 别名类所在包
   mapper-locations:
   - classpath:mybatis/mapper/**/*.xml  #mapper映射文件
   
spring:
   application:
    name: microservicecloud-dept
   datasource: 
    type: com.alibaba.druid.pool.DruidDataSource       #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          #mysql驱动包
    url: jdbc:mysql://localhost:3307/cloudDB01          #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5                                  #初始化连接数
      max-total: 5
      max-wait-millis: 200
   
   
  
